### ISSUE TITLE
Swift Conversions - Potential Issues

### ISSUE THREAD

**Issue by larson-carter** [solid-software/flutter_vlc_player#15]
@solid-software 

Are there any issues that I should be expected to encounter when converting to swift?

- Will the Pods give me any issues

- Will it be easier to add new features under swift and use Obj-C headers?

**Comment by solid-software** [comment]
I've checked with the dev and we are not sure. Most likely (if you want to convert it to swift) you need to try and see how it goes. Or maybe somebody else from community can answer.

**Comment by solid-software** [comment]
now we have limited experience with swift so I'm not sure if we can be helpful at the moment

**Comment by NBTX** [comment]
@solid-software having investigated, we've concluded (and been advised) that it would be easier to rebuild the project with Swift rather than Objective C and re-incorporate the Android and Dart code that way. Would you like us to set that up and add you to a repository?

If you'd prefer we can PR the code from the new repository back into here.

**Comment by solid-software** [comment]
Whatever works best for you - I hope that we'll have some time to fix some of the issues soon. Do you have any timeframe for your work?

**Comment by NBTX** [comment]
@solid-software I'm going to try my hand at an implementation tonight, so I'll be able to let you know by tomorrow a relatively accurate time frame.
