### ISSUE TITLE
Complete Flutter VLC Player Rewrite To Support V2 Plugins

### ISSUE THREAD

**Issue by mitchross** [solid-software/flutter_vlc_player#158]
Hi @solid-software 

@alr2413 and I have been hard at work past few months rewriting VLC plugin from scratch to support plugin v2. See https://medium.com/flutter/modern-flutter-plugin-development-4c3ee015cf5a

Here we have done a few things.

- Leverages V2 Android Flutter Plugin design pattern. 
- All VLC features enabled.
- Flutter Platform Interface to support any platform. The platform interface allows for platform specific implementation, ie web, desktop, linux, ios, android. Currently only iOS and Android are supported.
- Flutter Pigeon for type safe method calls. No more string matching on method calls! (https://pub.dev/packages/pigeon) 

Couple things.

We started a brand new repo for the work.  It can be found here -> https://github.com/alr2413/flt_vlc_player/tree/master/flutter_vlc_player

We need to your opinion a merge strategy back to this main repo.

We could make a branch off this repo, clear its contents, paste in our changed files and submit a PR. If thats good with you, we will do that. If you have a different suggestion, please let us know.

**Comment by alr2413** [comment]
ping @solid-software

**Comment by solid-software** [comment]
Hi, @mitchross @alr2413,

great job here and awesome improvements! Very impressed!

As for merge: it looks like there is no way to preserve history currently in GitHub: https://github.com/isaacs/github/issues/900, so that means that we should follow your suggestion. Let's create a new PR with the changes and we'll see if somebody from the community has any suggestions. We'll think about this a little bit more as well.

I am looking forward to it.
Thanks!

**Comment by mitchross** [comment]
https://github.com/solid-software/flutter_vlc_player/pull/159

**Comment by mitchross** [comment]
merged
