### ISSUE TITLE
7.1.5 compilation issues

### ISSUE THREAD

**Issue by itforgeuk** [solid-software/flutter_vlc_player#333]
Hi, 

I'm getting the following error in a fresh project:

```dart
../../../.pub-cache/hosted/pub.dartlang.org/flutter_vlc_player-7.1.5/lib/src/vlc_app_life_cycle_observer.dart:12:29: Error: Method 'addObserver' cannot be called on 'WidgetsBinding?' because
it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addObserver(this);
```

```
sdk: ">=2.16.1 <3.0.0"

[✓] Flutter (Channel stable, 2.10.3, on macOS 12.4 21F79 darwin-x64, locale en-GB)
    • Flutter version 2.10.3 at /Users/xxx/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 months ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-31, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.67.2)
    • VS Code at /Users/xxx/Desktop/V Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • iPad Air (5th generation) (mobile) • 28F0BEC1-EBE8-455E-8123-A3E4AC258ABF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

Is this null safe support issue?

Thanks

**Comment by ripeyd** [comment]
../../../Library/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_vlc_player-7.1.5/lib/src/vlc_app_life_cycle_observer.dart:12:29: Error: Method 'addObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Library/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addObserver(this);
                            ^^^^^^^^^^^
../../../Library/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_vlc_player-7.1.5/lib/src/vlc_app_life_cycle_observer.dart:32:29: Error: Method 'removeObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Library/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.removeObserver(this);
------------------------------------------------------------------------------------
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.4 21F79 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2022.1)
[✓] VS Code (version 1.67.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by ripeyd** [comment]
The solution
Upgrade Flutter to V3.0.1

**Comment by itforgeuk** [comment]
Thanks, @ripeyd upgrading flutter to 3.0.1 fixes my issue. I kept `sdk: ">=2.16.1 <3.0.0"` as it was.
